### ISSUE TITLE
Infinite errors when browserlink not defined

### ISSUE THREAD

**Issue by alexdresko** [madskristensen/WebEssentialsChrome#2]
I believe this should be `||` instead of `|`. I noticed this morning that my page was throwing thousands of errors, and it didn't look like it was going to stop anytime soon. 

![image](https://cloud.githubusercontent.com/assets/333022/26059661/89d05d62-3950-11e7-9252-6d74c5854f5c.png)

Discovered that the errors would stop if I disabled the WEC extension. Then discovered that BrowserLink wasn't properly connecting to SignalR. That lead me to this link: http://stackoverflow.com/questions/23049670/is-it-true-that-asp-net-mvc-browser-link-does-not-work-for-https-ssl-url

Following the instructions in the accepted answer fixed the SignalR issue, so I re-enabled the WEC extension and everything started working well again. 

Hope that makes sense. I have to go to a meeting now.

**Comment by madskristensen** [comment]
This is now fixed
