### ISSUE TITLE
Publish this extension to the Windows Store for Microsoft Edge

### ISSUE THREAD

**Issue by aberus** [madskristensen/WebEssentialsChrome#3]
Please publish this extension to Windows Store, so we can use it in Microsoft Edge.

**Comment by leniency** [comment]
Source code looks like Mads started but didn't get it onto the store?

Also with the new Chromium-based version of Edge, I tested the extension out and appears to work perfectly:

- [Downloaded the Dev Channel version](https://www.microsoftedgeinsider.com/en-us/)
- Cloned this git repo
- In Edge extensions, turned on dev mode
- Clicked "Load Unpacked" and selected this directory from the cloned project: "src/app"
- Works, at least with the Browser Link Inspector.
