### ISSUE TITLE
Chrome: "The message port closed before a response was received."

### ISSUE THREAD

**Issue by jerone** [madskristensen/WebEssentialsChrome#4]
This extension is throwing the following exception in the Developer Tools Console on every page I run, while this extension is enabled.

![image](https://user-images.githubusercontent.com/55841/52779543-aecd9d00-3048-11e9-862b-24e119703fb6.png)

A bit of Googling brought me to https://github.com/mozilla/webextension-polyfill/issues/130, and https://stackoverflow.com/a/43156470/108448 where solutions to the same problem was found.

---

_Microsoft Visual Studio Professional 2017 - Version 15.9.7 - VisualStudio.15.Release/15.9.7+28307.423
Microsoft .NET Framework - Version 4.7.03062
Google Chrome - Version 72.0.3626.109 (Official Build) (64-bit)
Web Essentials (Chrome extension) - Version 1.1_

**Comment by Murphybro2** [comment]
I can back this up. I'm having the same issue. It goes away if I disable the extension but I'd quite like to keep it on.

**Comment by jerone** [comment]
Friendly ping to @madskristensen in case you missed this issue. 😊

**Comment by burakt91** [comment]
Another friendly ping from me 😊 The issue still continues.
